config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'

  match '/auth/:provider/callback', to: 'users#callback', via: [:get, :post]
  get 'users/signout'


  resources :meets do
    resources :assistances, only: %i[new create]
    resources :tasks, only: %i[new create]
    resources :plans, only: :create, defaults: {format: 'js'}, controller: "meets/plans"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asisstances_task.rb
class AsisstancesTask < ApplicationRecord
  belongs_to :assistance
  belongs_to :task
end

app/models/assistance.rb
class Assistance < ApplicationRecord
  belongs_to :meet
  has_and_belongs_to_many :tasks

  validates :email, presence: true, format: {
                                      with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
                                      :message => 'no válido' }
end

app/models/meet.rb
class Meet < ApplicationRecord
  has_many :assistances
  has_many :tasks, through: :assistances

  has_rich_text :notes
  has_rich_text :protocol
  has_rich_text :agenda

  validates :nombre, presence: true
end

app/models/secretary.rb
class Secretary < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :assistances
  belongs_to :secretary

  validates :assistances, presence: true
  validates :nombre, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: %w[show update]

  def index
    @meets = Meet.all
  end

  def show
    @assistances = @meet.assistances
    @task = Task.new
  end

  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.new(meet_params)
    if @meet.save
      redirect_to new_meet_assistance_path(@meet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @meet.update(meet_params)
    if @meet.save
      redirect_to meet_path(@meet, anchor: set_anchor)
    else
      render :show
    end
  end

  private

  def meet_params
    params.require(:meet).permit(:nombre, :tipo, :fecha, :lugar, :notes, :agenda, :protocol)
  end

  def set_meet
    @meet = Meet.find(params[:id])
  end

  def set_anchor
    return "agenda"   if !params["meet"]["agenda"].nil?
    return "protocol" if !params["meet"]["protocol"].nil?
    return "notes"    if !params["meet"]["notes"].nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_meet, only: %w[create]

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to meet_path(@meet,  anchor: "tasks-title")
    else
      render "meets/show"
    end
  end

  private

  def task_params
    params.require(:task).permit(:nombre, :descripcion, :fecha, :secretary_id, assistance_ids: [] )
  end

  def set_meet
    @meet = Meet.find(params[:meet_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistances_helper.rb
module AssistancesHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Toma nota Actas Reuniones| Toma nota y delega las tareas que surgen de las reuniones.</title>
    <meta name="description" content="Ten trasabilidad de las reuniones y delega de forma sencilla con Microsoft planner las diferentes responsabilidades que fueron asignadas.">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta content="width=device-width, initial-scale=1" name="viewport" />

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Seguimiento Reuniones">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="theme-color" content="#FDC3AB">
    <link rel="manifest" href="/manifest.json">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
Hello from home

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex justify-content-space-around">
  <%= link_to meets_path, class: "navbar-brand" do %>
    <%= image_tag "logo_gob.jpg" %>
  <% end %>

  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Cerrar sesión", users_signout_path, class: "dropdown-item text-right" %>
        </li>
      </ul>
    </div>
  <% end %>
</div>