config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'

  match '/auth/:provider/callback', to: 'users#callback', via: [:get, :post]
  get 'users/signout'


  resources :meets do
    resources :assistances, only: %i[new create]
    resources :tasks, only: %i[new create]
    resources :plans, only: :create, defaults: {format: 'js'}, controller: "meets/plans"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asisstances_task.rb
class AsisstancesTask < ApplicationRecord
  belongs_to :assistance
  belongs_to :task
end

app/models/assistance.rb
class Assistance < ApplicationRecord
  belongs_to :meet
  has_and_belongs_to_many :tasks

  validates :email, presence: true, format: {
                                      with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
                                      :message => 'no válido' }
end

app/models/meet.rb
class Meet < ApplicationRecord
  has_many :assistances
  has_many :tasks, through: :assistances

  has_rich_text :notes
  has_rich_text :protocol
  has_rich_text :agenda

  validates :nombre, presence: true
end

app/models/secretary.rb
class Secretary < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :assistances
  belongs_to :secretary

  validates :assistances, presence: true
  validates :nombre, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method [:current_user, :user_signed_in?]

  private

  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/controllers/assistances_controller.rb
class AssistancesController < ApplicationController
  before_action :set_meet, only: %w[new create]

  def new
    @assistance = Assistance.new
  end

  def create
    @assistance = Assistance.new(assistance_params)
    @assistance.meet = @meet
    if @assistance.save
      redirect_to new_meet_assistance_path(@meet)
    else
      render :new
    end
  end

  private

  def set_meet
    @meet = Meet.find(params[:meet_id])
  end

  def assistance_params
    params.require(:assistance).permit(:email, :meet_id)
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meets/excel_rows_controller.rb
class Meets::ExcelRowsController < ApplicationController
  def index
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/meets/plans_controller.rb
class Meets::PlansController < ApplicationController
  before_action :set_meet, only: :create
  def create
  end

  private

  def set_meet
    @meet = Meet.find(params[:meet_id])
  end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: %w[show update]

  def index
    @meets = Meet.all
  end

  def show
    @assistances = @meet.assistances
    @task = Task.new
  end

  def new
    @meet = Meet.new
  end

  def create
    @meet = Meet.new(meet_params)
    if @meet.save
      redirect_to new_meet_assistance_path(@meet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @meet.update(meet_params)
    if @meet.save
      redirect_to meet_path(@meet, anchor: set_anchor)
    else
      render :show
    end
  end

  private

  def meet_params
    params.require(:meet).permit(:nombre, :tipo, :fecha, :lugar, :notes, :agenda, :protocol)
  end

  def set_meet
    @meet = Meet.find(params[:id])
  end

  def set_anchor
    return "agenda"   if !params["meet"]["agenda"].nil?
    return "protocol" if !params["meet"]["protocol"].nil?
    return "notes"    if !params["meet"]["notes"].nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_meet, only: %w[create]

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to meet_path(@meet,  anchor: "tasks-title")
    else
      render "meets/show"
    end
  end

  private

  def task_params
    params.require(:task).permit(:nombre, :descripcion, :fecha, :secretary_id, assistance_ids: [] )
  end

  def set_meet
    @meet = Meet.find(params[:meet_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :set_user_variables, only: :create
  # after_action :set_session_users, only: :create

  def callback
    @data = request.env['omniauth.auth']

    create
  end

  def signout
    reset_session
    flash[:notice] = "Sesión cerrada con éxito"
    redirect_to root_url
  end

  private

  def create
    set_user_variables
    unless user_exists?
      @user = User.new(
                    graph_token: @graph_token_hash[:token],
                    user_name: @user_name,
                    user_email: @user_email)
      if @user.save!
        set_session_users
        flash[:notice] = "Usuario creado con éxito"
        redirect_to meets_path
      end
    else
      set_session_users
      flash[:notice] = "Sesión iniciada con éxito"
      redirect_to meets_path
    end
  end

  def set_user_variables
    @graph_token_hash = @data.dig(:credentials)
    @user_name = @data.dig(:extra, :raw_info, :displayName)
    @user_email = @data.dig(:extra, :raw_info, :mail) ||
                           @data.dig(:extra, :raw_info, :userPrincipalName)
  end

  def user_exists?
    !User.find_by(user_email: @user_email).nil?
  end

  def set_session_users
    @user = User.find_by(user_email: @user_email) if user_exists?

    session[:user_id] = @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistances_helper.rb
module AssistancesHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meets/excel_rows_helper.rb
module Meets::ExcelRowsHelper
end

app/helpers/meets/plans_helper.rb
module Meets::PlansHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meets/create.html.erb
<h1>Meets#create</h1>
<p>Find me in app/views/meets/create.html.erb</p>

app/views/meets/edit.html.erb
<h1>Meets#edit</h1>
<p>Find me in app/views/meets/edit.html.erb</p>

app/views/meets/excel_rows/index.js.erb
// alert("Hola Mundo!");
// borremos todos los párrafos
// $('p').remove();
import { AuthenticationProvider } from "@microsoft/microsoft-graph-client";

class MyAuthenticationProvider implements AuthenticationProvider {
  /**
   * This method will get called before every request to the msgraph server
   * This should return a Promise that resolves to an accessToken (in case of success) or rejects with error (in case of failure)
   * Basically this method will contain the implementation for getting and refreshing accessTokens
   */
  public async getAccessToken(): Promise<string> {}
}
import { MyAuthenticationProvider } from "./MyAuthenticationProvider";

let clientOptions: ClientOptions = {
  authProvider: new MyCustomAuthenticationProvider(),
};
const client = Client.initWithMiddleware(clientOptions);

app/views/meets/index.html.erb
<div class="meets-container">
  <h1>
    <i class="fas fa-building"></i>
    Tus reuniones
  </h1>
  <div class="row">
    <%@meets.each do |meet| %>
      <div class="col-xs-12 col-sm-3">
        <%= link_to meet_path(meet) do %>
          <div class="card">
            <div class="card-description">
              <h2><%= meet.nombre %></h2>
              <p><%= meet.tipo %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="col-xs-12 col-sm-3">
      <%= link_to new_meet_path, class:"add-new-button" do %>
          <p>Crea una nueva reunion</p>
          <i class="fas fa-plus-circle"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/meets/new.html.erb
<div class="container mt-4">
  <h2>
    Ingresa los datos de la nueva reunión
  </h2>
  <%= simple_form_for @meet do |f| %>
    <%= f.input :nombre%>
    <%= f.input :tipo %>
    <%= f.input :fecha, as: :date, html5: true %>
    <%= f.input :lugar %>
    <%= f.button :submit, class:"btn btn-primary" %>
  <% end %>
</div>

app/views/meets/plans/create.js.erb
alert("Hello! I am an alert box!!");
console.log('prueba + <%= @meet.nombre %>');

app/views/meets/show.html.erb
<div class="container mt-4">
  <div class="meet-grid">
    <div class="meeting-general-info">
      <div class="card mb-4 mt-4">
        <div class="card-body meet-description text-center">
          <h1>
            <%= @meet.nombre %>
          </h1>
          <h4>
            <% unless @meet.tipo.nil?  %>
              Tipo de reunión: <%= @meet.tipo %>
            <% end %>
          </h4>
          <h6>
            <% unless @meet.tipo.nil? %>
              Fecha: <%= @meet.fecha.strftime("%F")  %>
            <% end %>
          </h6>
          <h6>
            <% unless @meet.lugar.nil?  %>
              Lugar: <%= @meet.lugar %>
            <% end %>
          </h6>
        </div>
      </div>
      <h4 class="mt-4 mb-4 pl-2">
        Ingresa los datos de la reunión a continuación:
      </h4>
      <div class="card mb-4">
        <div class="card-body meet-notes" id="agenda">
          <h3>
            Orden del día
          </h3>
          <%= simple_form_for @meet, remote: true do |f| %>
            <%= f.rich_text_area :agenda, class:"mb-4" %>
            <%= f.button :submit, class:"btn btn-secondary", value:"Actualizar"%>
          <% end %>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body meet-notes" id="protocol">
          <h3>
            Desarrollo de la reunión
          </h3>
          <%= simple_form_for @meet, remote: true do |f| %>
            <%= f.rich_text_area :protocol, class:"mb-4" %>
            <%= f.button :submit, class:"btn btn-secondary", value:"Actualizar"%>
          <% end %>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body meet-notes" id="notes">
          <h3>
            Notas de la reunión
          </h3>
          <%= simple_form_for @meet, remote: true do |f| %>
            <%= f.rich_text_area :notes, class:"mb-4" %>
            <%= f.button :submit, class:"btn btn-secondary", value:"Actualizar"%>
          <% end %>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body meet-tasks">
          <h3 id="tasks-title">
            Tareas de la reunión
          </h3>
          <div class="assistants-form mb-4 w-75">
            <%= simple_form_for([@meet, @task], remote: true) do |f| %>
              <%= f.input :nombre, label: "Nombre de la tarea" %>
              <%= f.input :descripcion, label: "Descripcion" %>
              <%= f.input :fecha, as: :date, html5: true, label: "Fecha de entrega" %>
              <%= f.association :secretary, collection: Secretary.order(:name), label: "Secretaria o Área responsable"%>
              <%= f.association :assistances, as: :check_boxes, collection: Assistance.where(meet: @meet), label_method: :email, label: "Responsables" %>
              <%= f.button :submit, class:"btn btn-secondary", value:"Añadir Tarea" %>
            <% end %>
          </div>
        </div>
      </div>
      <% if @meet.tasks.blank? %>
      <div class="card mb-4">
        <div class="card-body">
          Agrega la primera tarea la reunión
        </div>
      </div>
      <% else %>
        <div class="row">
          <% @meet.tasks.uniq.reverse.each do |task| %>
            <div class="col-xs-12 col-sm-6 d-flex align-items-stretch">
              <div class="card w-100 mb-2">
                <div class="card-body">
                  <div class="card-title">
                    <%= task.nombre %>
                  </div>
                  <div class="card-text">
                    <% task.assistances.each do |r| %>
                      <%= r.email %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="meeting-assistances mt-4 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-center">
            <h4>
              Asistentes de la reunión
            </h4>
          </div>
          <div class="card-text">
            <ul class="list-group list-group-flush text-center">
              <% @meet.assistances.each do |assistance| %>
                <li class="list-group-item pl-3 pr-3 pt-1 pb-1"><%= assistance.email %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div data-controller="meeting-plan">
    <button data-action="click->meeting-plan#create" class="btn btn-primary mt-4 mb-4">Guardar y delegar tareas en planner</button>
  </div>
</div>

app/views/meets/update.html.erb
<h1>Meets#update</h1>
<p>Find me in app/views/meets/update.html.erb</p>